"""Shared ChArUco board definition + detection helpers for
intrinsic_calibration.py and extrinsic_calibration.py.

ChArUco (chessboard + ArUco markers baked into the black squares) combines
a checkerboard's sub-pixel corner precision with ArUco's per-marker ID
robustness: a partially occluded/cropped view doesn't invalidate the whole
board -- each visible marker still identifies which square it sits next to.
It also has many correspondence points spread over a much larger physical
area than a single ArUco marker, which is usually a noticeably more stable/
accurate solvePnP.

Matches the board generated by generate_charuco_board.py -- keep
squares-x/squares-y/square-length/marker-length/aruco-dict identical
between board generation and calibration.
"""
import cv2


def make_charuco_board(squares_x, squares_y, square_length_m, marker_length_m,
                        dictionary_name="DICT_5X5_50"):
    """squares_x/squares_y: number of checkerboard squares along each side
    (not internal corners -- ChArUco boards are specified by total square
    count). marker_length_m must be smaller than square_length_m (the
    marker sits inside each black square with some white margin)."""
    if marker_length_m >= square_length_m:
        raise ValueError(
            f"marker_length_m ({marker_length_m}) must be smaller than "
            f"square_length_m ({square_length_m}) -- the marker sits inside each square.")
    dictionary = cv2.aruco.getPredefinedDictionary(getattr(cv2.aruco, dictionary_name))
    board = cv2.aruco.CharucoBoard((squares_x, squares_y), square_length_m, marker_length_m, dictionary)
    detector = cv2.aruco.CharucoDetector(board)
    return board, detector


def detect_charuco(detector, gray, min_corners=6):
    """Returns (charuco_corners, charuco_ids) or (None, None) if fewer than
    min_corners chessboard corners were confidently localized this frame."""
    charuco_corners, charuco_ids, _marker_corners, _marker_ids = detector.detectBoard(gray)
    if charuco_corners is None or charuco_ids is None or len(charuco_ids) < min_corners:
        return None, None
    return charuco_corners, charuco_ids


def draw_charuco_detection(display, charuco_corners, charuco_ids):
    if charuco_corners is not None and len(charuco_corners) > 0:
        cv2.aruco.drawDetectedCornersCharuco(display, charuco_corners, charuco_ids, (0, 255, 0))
